### ISSUE TITLE
Есть замечания по верстке

### ISSUE THREAD

**Issue by enslit** [Charity-project-bbbs/bbbs-project#5]
Я из команды, которая использует в работе вашу верстку при портировании ее на реакт. Есть замечания/предложения и тд. Вам интересна обратная связь от нас?

**Comment by SKKomolkina** [comment]
да, было бы отлично

**Comment by enslit** [comment]
Супер. Передам ребятам и сам буду кидать Issue

**Comment by AleksandraBab** [comment]
Саша, если вам удобнее, можете писать в тг @bobsbohnen. Будет оперативнее

**Comment by enslit** [comment]
Ок, тогда tg
